Desktop at UCL instruction improvements
UCL-RITS/ipls-workshop pull request #11
Opened 2021-04-28 14:33 UTC by alessandrofelder

Addresses @dpshelio and @mattgillucl 's comments on Slack! Thanks both!

2021-04-28 15:49 UTC, mattgillucl commented on _pages/setup/desktop.md
> +    [[ ! -f OLDHOME/.bash_profile ]] && cp $HOME/.bash_profile $OLDHOME
I don't think the cp command matches the description provided.

2021-04-28 15:52 UTC, mattgillucl requested changes
Please check the cp command and the description are in sync. I thik one of them is wrong

2021-04-28 16:00 UTC, dpshelio requested changes

2021-04-28 16:00 UTC, dpshelio commented on _pages/setup/desktop.md
> +This checks whether you had created a startup configuration in your home directory and copies to the new home on the n drive.
```suggestion
This checks whether you had created a startup configuration in your home directory before and if it doesn't exist, it copies it to the old home on the `c` drive.
```

I believe, however, that this explanation if given at all, should be either below the point where it happens or linked here with a footnote.
You could use `<sub>*</sub>` at the end of the step, and `<sub>*</sub>: explanation` at the bottom of the page.

2021-04-29 13:44 UTC, alessandrofelder commented
Latest changes should address your helpful comments now, @dpshelio and @mattgillucl ! Thank you!

2021-04-29 14:09 UTC, mattgillucl approved these changes
@alessandrofelder I think this is OK to merge now

2021-04-29 14:10 UTC, merged